- .changeset/happy-islands-sparkle.md
- .changeset/long-pants-fix.md
- packages/stg-definitions-v2/package.json
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-definitions-v2/src/types.ts
- pnpm-lock.yaml
- Adding contract networks config for EBI & Rarible
- Small cleanup: remove `ethers` dependency and replace with `@etgherproject/units` dev dependency
- Fix Safe URL for Rarible
> 🗞️ Add Safe config for EBI & Rarible

- packages/stg-evm-v2/devtools/config/mainnet/01/credit-messaging.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/token-messaging.config.ts
- Set delegates on mainnet Credit & TokenMessaging to the safe addresses
> 🧹 Add mainnet delegates

- packages/stg-evm-v2/package.json
- packages/stg-evm-v2/tasks/snapshot.ts
- pnpm-lock.yaml
- Add `@layerzerolabs/test-devtools` dev dependency that exports a useful `ENDPOINT_IDS` constant. We'll use these endpoint IDs to iterate over all possible peers of a contract.
- Add a stub of `AssetSnapshot` interface for stargate asset snapshot information
> 🧹 Stargate state snapshot: Assets for CreditMessaging [2/N]

- packages/stg-evm-v2/tasks/snapshot.ts
- Adding `owner`, `paused`, `addressConfig` and `oftPaths` to `AssetSnapshot`
> 🧹 Stargate state snapshot: Adding to assets' snapshots [3/N]

- packages/stg-evm-v2/devtools/src/erc20/schema.ts
- packages/stg-evm-v2/devtools/src/erc20/sdk.ts
- packages/stg-evm-v2/devtools/src/erc20/types.ts
- packages/stg-evm-v2/tasks/snapshot.ts
- Collect LP token information from assets when constructing the snapshot
> 🧹 Stargate state snapshot: Collection LP Token information [4/N]

- packages/stg-evm-v2/devtools/src/asset/sdk.ts
- packages/stg-evm-v2/devtools/src/asset/types.ts
- packages/stg-evm-v2/tasks/snapshot.ts
- Add `getToken` method to the `Asset` SDK
- Collect asset token information
> 🧹 Stargate state snapshot: Collection Token information [5/N]

- packages/stg-definitions-v2/src/constant.ts
> 🪲 Fix XChain chain ID in safe config

- .changeset/rude-bugs-confess.md
- packages/stg-evm-v2/package.json
Makes it way easier to utilize in forge projects rather than loading via ABI.
> 🗞️  include contract files in npm packaging

- packages/stg-evm-v2/devtools/config/mainnet/01/credit-messaging.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/token-messaging.config.ts
- Add missing connections for Credit & Token Messaging for Sei, Taiko & XChain
> 🪲 Add missing connections

- packages/stg-evm-v2/tasks/snapshot.ts
- Collect some of the `TokenMessaging` data in the `snapshot` task
> 🧹 Add stub of TokenMessaging snapshot collection

- .changeset/grumpy-rocks-shop.md
- packages/stg-definitions-v2/src/constant.ts
Incorrect dvn config for taiko's dvn
> 🐛 Fixing dvn config for taiko

- packages/stg-evm-v2/tasks/snapshot.ts
- Since we are now collecting assets and tokens twice (once for CreditMessaging, once for TokenMessaging), we can cache the collectors
> 🧹 Stargate state snapshot: Cache asset & ERC20 collectors [7/N]

- packages/stg-evm-v2/package.json
- packages/stg-evm-v2/src/oft-wrapper/OFTWrapper.sol
- packages/stg-evm-v2/src/oft-wrapper/interfaces/INativeOFT.sol
- packages/stg-evm-v2/src/oft-wrapper/interfaces/IOFTWrapper.sol
- pnpm-lock.yaml
> 🧵 copy in oft-wrapper contracts

- packages/stg-evm-v2/src/oft-wrapper/OFTWrapper.sol
- packages/stg-evm-v2/src/oft-wrapper/interfaces/IOFTWrapper.sol
Import specific identifiers rather than the whole file.
> 🧵 fix import statements for oft-wrapper contracts

- packages/stg-evm-v2/src/peripheral/oft-wrapper/OFTWrapper.sol
- packages/stg-evm-v2/src/peripheral/oft-wrapper/interfaces/IOFTWrapper.sol
- Add `DefaultBpsSet` and `OFTBpsSet` events to `OFTWrapper`
> 🧹 Add BPS events to OFTWrapper

- Makefile
- packages/stg-evm-v2/devtools/config/mainnet/01/oft-wrapper.config.ts
- packages/stg-evm-v2/devtools/src/oft-wrapper/config.ts
- packages/stg-evm-v2/devtools/src/oft-wrapper/factory.ts
- packages/stg-evm-v2/devtools/src/oft-wrapper/index.ts
- packages/stg-evm-v2/devtools/src/oft-wrapper/schema.ts
- packages/stg-evm-v2/devtools/src/oft-wrapper/sdk.ts
- packages/stg-evm-v2/devtools/src/oft-wrapper/types.ts
- packages/stg-evm-v2/devtools/tasks/constants.ts
- packages/stg-evm-v2/devtools/tasks/index.ts
- `OFTWrapper` devtools SDK & configurator
- A hardhat task to configure the `OFTWrapper`
> 🧹 OFT Wrapper SDK & configurator

- .changeset/forty-cherries-matter.md
- packages/stg-definitions-v2/src/constant.ts
> 🗞️ Clean up the constants files 

- .changeset/nice-ears-crash.md
- packages/stg-definitions-v2/src/constant.ts
Updated bus gas limits for:
base
optimism
metis
> 🐛 Update Bus gas limits

- packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
- Add missing asset config for USDC & USDT on Sei
- Add missing asset config for USDC on BSC
> 🪲 Add missing asset config for Sei & BSC

- .changeset/real-files-whisper.md
- The most recent deployments didn't get a changeset
> 🪲 Add missing changeset for Sei & BSC deployments

- .changeset/brown-poets-cheat.md
- packages/stg-definitions-v2/src/constant.ts
Bumping Gravity nativeDropAmount to 2
> Update gravity nativedrop

- .changeset/silly-coats-compete.md
- packages/stg-evm-v2/devtools/config/mainnet/01/rewarder.config.ts
Updated rewarder.config with new allocations for the stakingTokens for V2 incentives (for September 2024)
> update allocations for September

- .changeset/five-bats-ring.md
- packages/stg-evm-sdk-v2/README.md
- https://layerzerolabs.atlassian.net/browse/APPS-149
- Added README.md for package `stg-evm-sdk-v2`
- Added changeset
> 🧹 Add README for stg-evm-sdk-v2

- package.json
- packages/stg-evm-v2/package.json
- pnpm-lock.yaml
- Update `@layerzerolabs/lz-evm-sdk-v2` to version 3.0.7
> 🧹 Update dependencies

- packages/stg-devtools-evm-hardhat-v2/package.json
- packages/stg-devtools-v2/package.json
- packages/stg-evm-v2/package.json
- pnpm-lock.yaml
- Updating devtools dependency in all packages
> 🧹 Updated devtools dependency

- .changeset/lemon-colts-deliver.md
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/treasurer.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdt-token.config.ts
- Updated Vana USDT address
- Re-added vana usdt config that was previously commented out
> 🧹 Vana USDT config

- packages/stg-evm-v2/devtools/config/mainnet/01/oft-token.config.ts
- add OFT minter to islander WETH
> Islander WETH

- .changeset/good-ligers-prove.md
- packages/stg-definitions-v2/src/constant.ts
In this PR 
- peaq requires custom gas limits for bus & credit deliveries
> Peaq bus gas

- .changeset/gentle-jeans-taste.md
- packages/stg-definitions-v2/src/constant.ts
In this PR
* Add ETH Pool configuration
> Abstract Eth Pool

- .changeset/breezy-cougars-hope.md
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/treasurer.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdt-token.config.ts
In this PR
* Configure stgUSDT for Plume
> Plume usdt

- packages/stg-definitions-v2/src/constant.ts
In this PR
* Bump Superposition lzReceive Gas
* Bump Glue lzReceive Gas
* Bump Ink lzReceive Gas
* Bump Klaytn lzReceive Gas
> Bump gas configs

- .changeset/hot-eyes-reflect.md
- packages/stg-definitions-v2/src/constant.ts
In this PR
- update gnosis safe link
> Fix gnosis safe

- .changeset/fifty-eyes-argue.md
- packages/stg-definitions-v2/src/constant.ts
In this PR
* bump nativeDrop gasLimit for Peaq, Sei, Flare, Bera
> Native drop gaslimit

- .changeset/beige-scissors-study.md
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.eth.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdc.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.eth.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.usdc.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/oft-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/oft-wrapper.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/token-messaging.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/treasurer.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdc-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdt-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/utils.ts
- packages/stg-evm-v2/hardhat.config.ts
in this PR
- hydra USDC
- hydra USDT
- hydra WETH
> Goat mainnet

- .changeset/kind-apples-sort.md
- package.json
- packages/stg-definitions-v2/package.json
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.eth.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdc.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.eth.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.usdc.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/oft-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/oft-wrapper.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/token-messaging.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/treasurer.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdc-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdt-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/utils.ts
- packages/stg-evm-v2/hardhat.config.ts
- pnpm-lock.yaml
In this PR 
* Hydra USDC
* Hydra USDT
* Hydra WETH
> Story mainnet

- .changeset/proud-queens-admire.md
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.eth.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.eth.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/oft-wrapper.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/token-messaging.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/treasurer.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/utils.ts
- packages/stg-evm-v2/hardhat.config.ts
In this PR 
* ETH Pool on Unichain
> Unichain mainnet

- .changeset/wild-buckets-leave.md
- packages/stg-definitions-v2/src/constant.ts
Increase bus gas consumption for Arb & Story dst chains
> Arb & Story gas bump

- .changeset/eight-badgers-vanish.md
- package.json
- packages/stg-definitions-v2/package.json
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/oft-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/treasurer.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdc-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdt-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/utils.ts
- packages/stg-evm-v2/hardhat.config.ts
- pnpm-lock.yaml
Config for Plume phoenix Mainnet (98866) based on: 
- PLUME – native gas
- USDC.e
- USDT
- WETH
TODOs:
> plume phoenix config

- .changeset/lovely-fireants-promise.md
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/oft-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/treasurer.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdc-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdt-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/utils.ts
- packages/stg-evm-v2/hardhat.config.ts
Config for Nibiru (6900) based on: 
- USDC.e - oft
- USDT - oft
- WETH - oft 
TODOs:
> Nibiru mainnet config

- .changeset/nice-geese-jog.md
- packages/stg-definitions-v2/src/constant.ts
Bumping taxis into Unichain for large payloads
> Unichain bump

- .changeset/shiny-flowers-warn.md
- packages/stg-evm-v2/devtools/config/mainnet/01/rewarder.config.ts
In this PR
* re-add incentives on USDC & ETH on Ethereum mainnet
> Update Eth Rewards

- .changeset/rude-otters-report.md
- packages/stg-definitions-v2/src/constant.ts
Increase lzReceive gas for txns to PlumePhoenix
> Bump Plume Taxi Gas Config

- .changeset/dull-olives-study.md
- package.json
- packages/stg-definitions-v2/package.json
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.usdt.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/oft-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/treasurer.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/usdc-token.config.ts
- packages/stg-evm-v2/devtools/config/mainnet/utils.ts
- packages/stg-evm-v2/hardhat.config.ts
- pnpm-lock.yaml
Config for Botanix(3637) based on: 
- USDC.e - oft
- WETH - oft 
TODOs:
> Botanix mainnet config

- .github/workflows/reusable-check-config.yaml
fixes the secrets used in the actions introduced in the pr #366
> fix: set correct rpc

- .changeset/smooth-zoos-hear.md
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/chainsConfig/apexfusionnexus-mainnet.yml
- packages/stg-evm-v2/hardhat.config.ts
Config for Apex Fusion Nexus Mainnet (9069) based on: 
- USDC - oft
TODOs:
> ⚙️ [config] Apex fusion nexus mainnet

- .changeset/young-plants-worry.md
- package.json
- packages/stg-definitions-v2/package.json
- packages/stg-definitions-v2/src/constant.ts
- packages/stg-evm-v2/devtools/config/mainnet/01/chainsConfig/og-mainnet.yml
- packages/stg-evm-v2/hardhat.config.ts
- pnpm-lock.yaml
Config for )gMainnet (16661) based on: 
- WETH - oft
- USDT - oft
- USDC - oft
TODOs:
> ⚙️ [config] Og mainnet
