stargate-protocol/stargate-v2

.github/workflows/reusable-configure.yaml

- Add a github workflow that deploys, configures & transfers the mainnet contracts under devtools simulation
- This workflow can then be reused to produce a diff of the expected on-chain state

🧹 Add mainnet simulation

---

.changeset/metal-clocks-sneeze.md
packages/stg-definitions-v2/package.json
packages/stg-error-parser/package.json
packages/stg-evm-sdk-v2/package.json
packages/stg-evm-v2/devtools/config/sandbox/mint.allowance.config.ts
packages/stg-evm-v2/devtools/config/testnet/mint.allowance.config.ts
packages/stg-evm-v2/package.json

- Prepare packages for the first major version
- Fix import paths in `mint.allowance.config` that surfaced after the `exports` field has been added to `stg-definitions-v2`
- Bump the versions
- Make packages public

🗞️ Bump package versions to 1.0.0

---

packages/stg-evm-v2/tasks/balances.ts
packages/stg-evm-v2/tasks/index.ts

- Helper utility task to display account balances. Accepts a mandatory `--stage` argument that filters down the networks.

🧹 Display balances task

---

packages/stg-evm-v2/hardhat.config.ts

- The simulation nodes are having issues completing the large transactions in time. This results in the mainnet simulation failing on node timeout issues
- Large `timeout` has been added to the mainnet networks and to the anvil configuration of the simulation nodes

🪲 Simulation timeout issues

---

packages/stg-evm-v2/devtools/src/asset/sdk.ts
packages/stg-evm-v2/devtools/src/asset/types.ts
packages/stg-evm-v2/tasks/snapshot.ts

- Add `getStargateType` method to `Asset` SDK
- Collect `StargateType` from the assets when creating the snapshot

🧹 Stargate state snapshot: Collect asset type [6/N]

---

Makefile
packages/stg-evm-v2/DEPLOYMENT.md

- The storage initialization transactions are quite gas-intensive and should not be run in batched mode

🧹 Force the storage initialization not to be batched

---

.changeset/selfish-bulldogs-mix.md
packages/stg-evm-v2/package.json

- In hardhat projects the TypeScript situation is a bit tight - long story short, it is extremely cumbersome to setup `bundler`/`nodenext` TypeScript module resolution. Without this module resolution, it is impossible to use the `exports` field. However, when trying to import from `./dist/` paths, the TypeScript code completion fails.

🧹 Add ./dist to exports to support hardhat consumers

---

packages/stg-evm-v2/src/messaging/TokenMessaging.sol

Did not change the contract logic as it would require a subsequent audit to assert.  Instead, just clearly document the limitation.

chore:  document queue_capacity limitation

---

.github/workflows/reusable-gas-snapshot.yaml
.github/workflows/reusable-test.yaml

- Supply a default value for `RPC_URL_ETHEREUM_MAINNET` that's used for fork testing. This fixes PRs from external repos that didn't have access to repository secrets

🪲 Add default for ETH RPC URL

---

packages/stg-evm-v2/DEPLOYMENT.md

Fixed image link in `DEPLOYMENT.md`:
- Updated from `https://stargate.finance/media/images/og-image.jpg` to `https://stargate.finance/static/og-image.jpg`.

Fixed broken link in DEPLOYMENT.md

---

.changeset/neat-trainers-travel.md
packages/stg-definitions-v2/src/constant.ts
packages/stg-definitions-v2/src/types.ts
packages/stg-evm-v2/deploy/020-deploy-oft-wrapper.ts
packages/stg-evm-v2/ts-src/constants.ts

- Add `OFT_WRAPPER` configuration constant into `stg-definitions-v2`. This holds the default `bps` value as well as potential network overrides
- Add a deploy script for `OFTWrapper`. This deploy script will skip any networks not defined under `OFT_WRAPPER.networks`

🧵 OFTWrapper deploy script

---

packages/stg-evm-v2/deploy/009-deploy-treasurer.ts

- Skip `Treasurer` deployments if there is no `TokenMessaging` present. This is important if we are to add new networks with only `OFTWrapper` on them

🪲 Skip Treasurer deployments for networks with no TokenMessaging

---

packages/stg-evm-v2/src/peripheral/oft-wrapper/OFTWrapper.sol
packages/stg-evm-v2/src/peripheral/oft-wrapper/interfaces/IOFTWrapper.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/OFTWrapper.t.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/mocks/ERC20Mock.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/mocks/epv2/MockOFT.sol

- Adds an EnpointV2 specific OFTWrapper API.
- Adds a cross-chain test which effectively transfers tokens from A_EID to B_EID, checking accumulated fees along the way.

🧵 support EndpointV2 OFT in oft-wrapper

---

packages/stg-evm-v2/src/peripheral/oft-wrapper/OFTWrapper.sol
packages/stg-evm-v2/src/peripheral/oft-wrapper/interfaces/IOFTWrapper.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/OFTWrapper.t.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/mocks/epv2/MockOFT.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/mocks/oft/OFTMock.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/mocks/oft/OFTProxyMock.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/mocks/oftv2/OFTMock.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/mocks/oftv2/OFTProxyMock.sol

This is actually broken in the following three functions:
* estimateSendFee(...)
* estimateSendFeeV2(...)
* estimateSendFeeEpv2(...)
The latter two functions are released and deployed, so we must protect the interface.  It doesn't actually end up making a difference as the messaging fee is the same regardless of the bps configuration in the default implementation.  That said, it is not future proof for Adapter implementations in which the MessagingFee may vary based on the configured bps.
This PR fixes the implementation of all three.

🪲 estimateSendFee{,v2,Epv2}(...) do not take into account OFT-specific bps

---

packages/stg-definitions-v2/src/constant.ts
packages/stg-definitions-v2/src/types.ts
packages/stg-evm-v2/deploy/020-deploy-oft-wrapper.ts
packages/stg-evm-v2/src/peripheral/oft-wrapper/OFTWrapper.sol
packages/stg-evm-v2/src/peripheral/oft-wrapper/interfaces/IOFTWrapper.sol
packages/stg-evm-v2/test/unitest/peripheral/oft-wrapper/OFTWrapper.t.sol

This helps avoid caller applications to OFTWrapper from setting fee bps arbitrarily high.  This is not needed for the defaultBps, as only the owner can set that.

🪲 assert a cap for caller bps

---

.changeset/dry-fans-pull.md
packages/stg-definitions-v2/src/constant.ts
packages/stg-definitions-v2/src/types.ts
packages/stg-evm-v2/deploy/003-deploy-message.ts
packages/stg-evm-v2/devtools/config/utils.ts

- Make `tokenMessaging` and `creditMessaging` properties of network config optional. If they are bullish, messaging will not be deployed
- Move `queueCapacity` under `tokenMessaging` in the config

🧹 Make Credit & Token Messaging configs optional in network configuration

---

.changeset/fast-wombats-smell.md
packages/stg-definitions-v2/src/constant.ts
packages/stg-definitions-v2/src/types.ts
packages/stg-evm-v2/devtools/config/utils.ts

- Add `confirmations` to configuration types for token & credit messaging
- Set the confirmations to `50` for EBI

🧹 Specify confirmations for EBI

---

.github/workflows/on-main.yaml
.github/workflows/reusable-test.yaml

- Before we investigate the performance degradation of the gas profiling workflows, we disable them

🧹 Disable gas profiling workflows because we don't like them anymore

---

packages/stg-definitions-v2/package.json
packages/stg-devtools-evm-hardhat-v2/package.json
packages/stg-devtools-evm-hardhat-v2/src/credit-messaging/schema.ts
packages/stg-devtools-evm-hardhat-v2/src/token-messaging/schema.ts
packages/stg-devtools-v2/package.json
packages/stg-error-parser/package.json
packages/stg-evm-sdk-v2/package.json
packages/stg-evm-v2/package.json
pnpm-lock.yaml
turbo.json

- Unfortunately the `as const` feature of `@layerzerolabs/export-deployments` results in `TS7056 The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed` error. The package has been downgraded
- Since the build did not catch this error, the turbo pipeline has been improved and accounts for the global dependencies now - especially `pnpm-lock.yaml`
- The cleared cache also resulted in a TypeScript error related to the mismatch of the `lz-v2-utilities` package versions. Explicit type annotations were added to the schemas that were producing this error (credit & token messaging schemas)

🪲 Fix deployments export

---

.github/workflows/reusable-configure.yaml
Makefile
packages/stg-evm-v2/DEPLOYMENT.md

- Split the `configure-mainnet` `make` target into two
- `preconfigure-mainnet` can be run with a hot wallet, it will setup the OFT/USDC contracts
- `configure-mainnet` is then run after the ownership has been transferred and is run using the multisig
- The sequence of configuration then becomes:
- `preconfigure-mainnet`
- `transfer-mainnet`
- `configure-mainnet`

🧹 Split mainnet configuration target

---

packages/stg-evm-v2/package.json
pnpm-lock.yaml

- Bump the version of `@layerzerolabs/export-deployments` to fix a problem with TypeScript compiler & the size of the deployed artifacts. See [this PR](https://github.com/LayerZero-Labs/devtools/pull/953)

🪲 Bump @layerzerolabs/export-deployments

---

packages/stg-evm-v2/devtools/config/mainnet/01/oft-token.config.ts

- `ETH` was being configured as an OFT token for LightLink whereas in reality it's a native token

🪲 ETH Is not an OFT on LightLink

---

packages/stg-evm-v2/devtools/config/mainnet/01/feelib-v1.eth.config.ts

- Config for `FeeLibV1ETH` was missing on Lightlink.
- After merging, only `make transfer-mainnet` is required to rectify on chain

🪲 Add missing config for ETH FeeLib on Lightlink

---

Makefile
packages/stg-evm-v2/hardhat.config.ts

- Updated `Makefile` to call existing `lz:healthcheck:validate:rpcs` task before proceeding with configurations
- Note that this task will fail for sandbox rpcs if they are not running on localhost
- Updated klaytn testnet and zksync mainnet rpcs since they were not passing validation
**Example of what successful RPC validation looks like:**
```
ravina@Ravinas-MacBook-Pro stargate-v2 % LZ_ENABLE_EXPERIMENTAL_PARALLEL_EXECUTION=1 LZ_ENABLE_EXPERIMENTAL_BATCHED_WAIT=1 LZ_EXPERIMENTAL_WITH_SIMULATION=1 make configure-testnet CONFIGURE_ARGS_COMMON=--ci
pnpm --filter @stargatefinance/stg-evm-v2 run hardhat lz:healthcheck:validate:rpcs --config ./hardhat.config.ts --timeout 5000
> @stargatefinance/stg-evm-v2@1.1.3 hardhat /Users/ravina/github.com/stargate-v2-fixed/stargate-v2/packages/stg-evm-v2 …
```

🧹 Validate RPCs before configuring testnets and mainnets

---

packages/stg-evm-v2/devtools/config/mainnet/01/asset.usdt.config.ts
packages/stg-evm-v2/devtools/config/mainnet/01/oft-token.config.ts
packages/stg-evm-v2/devtools/config/mainnet/01/shared.ts
packages/stg-evm-v2/devtools/config/mainnet/01/treasurer.config.ts

- Due to token incompatibility, USDT is temporarily dropped from Peaq config

🧹 Drop USDT from Peaq mainnet config

---

packages/stg-error-parser/readme.md

In the description of the `parseError` function: "This function parses a given string for error and decodes it." It should be: "This function parses a given string for **an** error and decodes it."

🧹 Update readme.md

---

packages/stg-evm-v2/src/StargateOFT.sol
packages/stg-evm-v2/src/interfaces/IERC20Minter.sol

The Tether USDT contracts require the owner of the token contract to be the only minter allowed. For stargate, this means that the `StargateOFTUSDT` contract will be the owner and minter of the USDT token. 
However the `StargateOFTUSDT` contract currently does not support all `onlyOwner` functions of the USDT token contract -- it only supports mint and burn. Therefore, we will implement a `transferTokenOwnership` function to allow the option of temporarily transferring ownership if the unsupported `onlyOwner` functions on the USDT token contract are ever needed.
This is the extent of the change -- we do not need to worry about the eventual transfer of ownership to Tether which will revoke `StargateOFTUSDT`'s minting privileges because at that point, `StargateOFTUSDT` will be deprecated …

🧹 Add transferTokenOwnership function to StargateOFT

---

.changeset/cyan-deers-greet.md
packages/stg-definitions-v2/src/constant.ts

In this PR: 
Glue transactions are occasionally consuming more gas than our current configs. 
This PR introduces higher gas limits for sendCredits, nativeDrop and busRides

Bump Glue Gas configs

---

packages/stg-evm-v2/test/unitest/peripheral/zapper/StargateZapperV1.t.sol

After the Pectra update, EOAs can have code, which is causing `StargateZapperV1Test::test_RecoverToken` test to fail.
The issue is due to `StargateZapperV1Test` is forking mainnet in the [setup](https://github.com/stargate-protocol/stargate-v2/blob/391728d210074e97615b27a062c2eadeca7c0355/packages/stg-evm-v2/test/unitest/peripheral/zapper/StargateZapperV1.t.sol#L50), and in the [test_RecoverToken](https://github.com/stargate-protocol/stargate-v2/blob/391728d210074e97615b27a062c2eadeca7c0355/packages/stg-evm-v2/test/unitest/stargate/StargateBase.t.sol#L190) it tries to call `transfer` function in `vm.addr(1)`. 
`vm.addr(1)` is expected to be an EOA and successfully do the call, but since block [22447040](https://etherscan.io/tx/0x1db07e45d714389a77697fe88d1615a044ec997a4cd9bfec1f66ee220d5bd …

fix: test failure due to vm.addr(1) having code on mainnet 
